name: CI/CD with Reviewers

on:
  pull_request:
    types: [opened]
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:


  # --- Build Job ---
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  # --- Test Job ---
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Run unit tests
        run: dotnet test --configuration Release

  # --- Deploy Staging ---
  deploy-staging:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      - name: Deploy to Azure Web App (Staging)
        uses: azure/webapps-deploy@v2
        with:
          app-name: FunctionAppTesting
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '.'

  # --- Deploy Production ---
  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      - name: Deploy to Azure Web App (Production)
        uses: azure/webapps-deploy@v2
        with:
          app-name: FunctionAppTesting
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '.'
